# syntax=docker/dockerfile:1
FROM myoung34/github-runner:latest
LABEL maintainer="y.aotsuki@gmail.com"

COPY ./sources.list /etc/apt/
RUN apt update && apt install -y vim parallel pv \
jq build-essential zstd xz-utils cmake asciidoc binutils \
bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip \
zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs \
git-core gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev \
texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev \
autoconf automake libtool autopoint ccache curl wget vim nano python2.7 \
python3 python3-pip python-ply python3-ply haveged lrzsz device-tree-compiler \
scons antlr3 gperf intltool mkisofs rsync swig wget
RUN cd /actions-runner && wget http://launchpadlibrarian.net/465140146/btrfs-progs_5.4.1-2_amd64.deb && apt install -y btrfs-progs_5.4.1-2_amd64.deb
WORKDIR /_work

ENTRYPOINT ["/entrypoint.sh"]
CMD ["./bin/Runner.Listener", "run", "--startuptype", "service"]