name: test_shell

on:
  # schedule:
  #   # daily build on UTC+8 7:30
  #   - cron:  '30 18 * * 2,5'
  repository_dispatch:
  workflow_dispatch:
    inputs:
      device:
        description: 'select device to build'
        default: 'r4s'
        required: false
      branch:
        description: 'seleclt openwrt branch'
        default: 'master'
        required: false

jobs:

  build_packages_2:
    name: Build ${{ github.event.client_payload.device || github.event.inputs.device }} packages step 2
    runs-on: ubuntu-20.04
    env:
      DEVICE: ${{ github.event.client_payload.device || github.event.inputs.device }}
      BRANCH: ${{ github.event.client_payload.branch || github.event.inputs.branch }}
      TG: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    if: github.repository_owner=='aotsukiqx' 
    steps:    
      - name: Restore status
        run: |
          echo "PWD: $(pwd)"
          sudo apt update;
          sudo apt -y --no-upgrade --no-install-recommends install nodejs npm
          npm install -g argon2-cli
          
          echo "Gen pass..."
          echo -n "thisismypassword" | npx argon2-cli -e
